# Generated by Django 2.0.7 on 2018-07-10 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='date_published',
            field=models.DateTimeField(),
        ),
    ]
