# Generated by Django 2.0.7 on 2018-07-11 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180710_2319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='date_created',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='date_published',
            new_name='publish_date',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='date_updated',
            new_name='update_date',
        ),
    ]
