# Generated by Django 2.0.7 on 2018-07-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180711_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Final', 'Final')], default='Draft', max_length=10),
        ),
    ]
