# Generated by Django 2.0.7 on 2018-07-11 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180711_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='publish_date',
        ),
    ]
