# Generated by Django 2.0.7 on 2018-07-10 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffmember',
            old_name='title',
            new_name='job_title',
        ),
    ]
