# Generated by Django 2.0.7 on 2018-07-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20180710_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='image',
            field=models.ImageField(blank=True, upload_to='staff_pics'),
        ),
    ]
