# Generated by Django 2.0.7 on 2018-07-10 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_staffmember_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffmember',
            old_name='image',
            new_name='photo',
        ),
    ]
