# Generated by Django 2.0.7 on 2018-07-10 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20180710_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='publications',
        ),
    ]
